spin_manifest_version = "1"
authors = ["lee-orr <lee-orr@users.noreply.github.com>"]
description = ""
name = "example-app"
version = "0.1.0"

[trigger]
type = "message"

[trigger.brokers.test]
broker_type = "InMemoryBroker"

[trigger.brokers.test.gateway.Http]
port = 3_005

[trigger.brokers.secondary]
broker_type = { Redis = "redis://redis:6379" }


[trigger.brokers.secondary.gateway.Http]
port = 3_006
websockets = "TextBody"


[[component]]
id = "hello"
source = "../target/wasm32-wasi/release/example_app.wasm"
allowed_http_hosts = []
[component.trigger]
broker = "test"
subscription = "hello*"
result = { default_broker = "secondary", default_subject = "goodbye" }
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "goodbye"
source = "../target/wasm32-wasi/release/example_app.wasm"
allowed_http_hosts = []
[component.trigger]
broker = "secondary"
subscription = "goodbye"
result = { default_broker = "test", default_subject = "sink" }
[component.build]
command = "cargo build --target wasm32-wasi --release"
