spin_manifest_version = "1"
authors = ["lee-orr <lee-orr@users.noreply.github.com>"]
description = ""
name = "example-app"
version = "0.1.0"

[trigger]
type = "message"

[trigger.brokers.test]
broker_type = "InMemoryBroker"

[trigger.brokers.test.gateway.Http]
port = 3_005
request_response = "Json"

[trigger.brokers.secondary.broker_type]
Redis = "redis://redis:6379"


[trigger.brokers.secondary.gateway.Http]
port = 3_006
websockets = "TextBody"
request_response = "Json"


[[component]]
id = "hello"
source = "./target/wasm32-wasi/release/example_app.wasm"
allowed_http_hosts = []
[component.trigger]
broker = "test"
[component.trigger.subscription.Topic]
topic = "hello.*"
result = { default_broker = "secondary", default_subject = "good.bye" }
[component.build]
command = "cargo build --target wasm32-wasi --release -p example-app"

[[component]]
id = "goodbye"
source = "./target/wasm32-wasi/release/example_app.wasm"
allowed_http_hosts = []
[component.trigger]
broker = "secondary"
[component.trigger.subscription.Topic]
topic = "good.bye"
result = { default_broker = "test", default_subject = "sink" }
[component.build]
command = "cargo build --target wasm32-wasi -p example-app --release"

[[component]]
id = "request"
source = "./target/wasm32-wasi/release/request_response_demo.wasm"
allowed_http_hosts = []
[component.trigger]
broker = "secondary"
[component.trigger.subscription.Request]
path = "test/*/hello"
method = "POST"
[component.build]
command = "cargo build --target wasm32-wasi --release -p request-response-demo"

[[component]]
id = "queue_1"
source = "./target/wasm32-wasi/release/queue_app.wasm"
allowed_http_hosts = []
[component.trigger]
broker = "secondary"
[component.trigger.subscription.Queue]
topic = "test"
group = "queue"
result = { default_broker = "test", default_subject = "sink" }
[component.config]
queue_id = "1"
[component.build]
command = "cargo build --target wasm32-wasi -p queue-app --release"

[[component]]
id = "queue_2"
source = "./target/wasm32-wasi/release/queue_app.wasm"
allowed_http_hosts = []
[component.trigger]
broker = "secondary"
[component.trigger.subscription.Queue]
topic = "test"
group = "queue"
result = { default_broker = "test", default_subject = "sink" }
[component.config]
queue_id = "2"
[component.build]
command = "cargo build --target wasm32-wasi -p queue-app --release"