manifest_version = "1"
id = "message-component"
description = "Simple Messaging Component using Rust"
tags = ["messaging", "rust"]


[add_component.snippets]
component = "component.txt"

[parameters]
project-description = { type = "string", prompt = "Description", default = "" }
trigger-broker = { type = "string", prompt = "Triggering Broker", default = "primary" }
trigger-topic = { type = "string", prompt = "Subscription", default = "hello.*" }
result-broker = { type = "string", prompt = "Default Result Broker", default = "primary" }
result-topic = { type = "string", prompt = "Default Result Topic", default = "goodbye" }
