manifest_version = "1"
id = "redis-broker"
description = "Redis Message Broker for Spin Message Trigger"
tags = ["messaging", "rust"]

[add_component.snippets]
component = "component.txt"

[parameters]
broker-url = { type = "string", prompt = "Broker Url", default = "redis://redis:6379" }
