[package]
edition = "2021"
name = "message-macro"
version = "0.1.0"

[lib]
name = "message_macro"
proc-macro = true

[features]
default = []

[dependencies]
anyhow = "1"
bytes = "1"
proc-macro2 = "1"
quote = "1.0"
syn = { version = "2", features = [ "full" ]}
wit-bindgen = "0.6"