name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: test
  cancel-in-progress: true

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install Targets
      run: rustup target install wasm32-unknown-unknown && rustup target install wasm32-wasi
    - name: Run tests
      run: cargo test --verbose
      
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install Targets
        run: rustup target install wasm32-unknown-unknown && rustup target install wasm32-wasi
      - uses: fxwiegand/apply-clippy-lints@v1.0.4
      
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting of Rust code with rustfmt
        uses: actions-rust-lang/rustfmt@v1.1.0
  
  build:
    needs: 
      - test
      - clippy
      - fmt
    uses: ./.github/workflows/build.yml



